#!/usr/bin/env bash
# Export all C4 views from the authoritative LikeC4 model into GitHub-rendered
# Mermaid. A disposable source copy prevents export from overwriting the
# hand-authored architecture/README.md. Requires npm ci first.
set -euo pipefail

mode="${1:---write}"
case "$mode" in
  --write|--check) ;;
  *) echo "usage: $0 [--write|--check]" >&2; exit 2 ;;
esac

source_dir="dist/likec4-markdown-source"
output="docs/architecture/rendered.md"
mkdir -p "$source_dir"
cp docs/architecture/model.c4 docs/architecture/views.c4 "$source_dir/"
npm exec -- likec4 export markdown "$source_dir"
test -s "$source_dir/README.md"

{
  printf '%s\n\n' '<!-- Generated by scripts/generate-architecture-markdown.sh from docs/architecture/{model,views}.c4. Do not edit manually. -->'
  cat "$source_dir/README.md"
} > "dist/likec4-rendered.md"

if [[ "$mode" == "--check" ]]; then
  if [[ ! -f "$output" ]]; then
    echo "::error::Missing generated $output; run bash scripts/generate-architecture-markdown.sh --write" >&2
    exit 1
  fi
  diff -u "$output" "dist/likec4-rendered.md"
else
  cp "dist/likec4-rendered.md" "$output"
fi
